### PR TITLE
Change tag handling to support generation for Alpha API

### PR DESCRIPTION
**Pull request by joshand**
In the current build script, we are currently limiting to first 10 tags, which excluded environmental. I've expanded this to 11 in order to stop the crash. This might result in correct environmental APIs, but I've not actually tested this.

### CODE REVIEW

**Review by TKIPisalegacycipher — CHANGES_REQUESTED** [review]
Line 127 ends with "7 products" -- this can now be "8 products".

**Comment by joshand** [comment]
Re: meraki/api/batch/__init__.py

warning: CRLF will be replaced by LF in meraki/api/batch/__init__.py.
The file will have its original line endings in your working directory

**Comment by TKIPisalegacycipher** [comment]
Thank you for submitting this. I tested these changes, and it breaks library generation for GA. We will not make these changes for the time being.

**Comment by joshand** [comment]
To preserve library generation for GA/Beta branches, I moved this logic to an optional flag (-p <num>). So, to build for Alpha, you can use the following syntax:
python3 generate_library.py -o 608548899648439349 -v 1 -p 11

Using the regular generation command will continue to operate as usual for GA/Beta builds.
python3 generate_library.py -o 608548899648439349 -v 1

**Comment by TKIPisalegacycipher** [comment]
Thanks @joshand ! This is a step in the right direction. However, there are other parts (like action batches) which would require additional logic. We will undertake this effort when the MT team is ready to GA their endpoints. In the meantime, it's hard to justify the additional work and testing that would be required to integrate this into the main branch. These commits make more sense in a separate development branch. Would you like to open a devel branch?

**Pull request closed without merging**
