### PR TITLE
Aiohttp

### PR DESCRIPTION
**Pull request by coreGreenberet**
This PR will add a submodule to use aiohttp instead of the current requests module
I've also provided an aio version of the org_wide_clients.py example

### CODE REVIEW

**Comment by coreGreenberet** [comment]
> 
> 
> Might want to change that API key friend!

It's already removed. You gave me almost a heart attack. I thought I did it again :'D

**Comment by coreGreenberet** [comment]
@shiyuechengineer do you have any timeline for merging this?

**Comment by shiyuechengineer** [comment]
Hi @coreGreenberet, this should be merged in the next release, so first week of March. Thank you again for your contributions!!

**Comment by coreGreenberet** [comment]
hi @shiyuechengineer thanks for the update =D I'm looking forward to it^^

**Comment by shiyuechengineer** [comment]
@coreGreenberet, your files have been added into the latest update. Thank you for your contributions!

**Pull request closed without merging**
